project:
  type: website
  output-dir: _site
  resources:
  - docs/favicon.svg

  - .grafts-cache/build/my-first-graft/**/*.html
filters:
- docs/site-build.lua

website:
  title: "quarto-test-01"
  description: "Skeleton docs for branch-based Quarto builds."
  favicon: docs/favicon.svg
  # repo-url: https://github.com/YOUR_ORG/YOUR_REPO
  # repo-actions: [source, issue]
  page-footer:
    right: "Last build: {{< meta site_build >}}"

  navbar:
    title: "quarto-test-01"
    logo: docs/favicon.svg
    logo-alt: "quarto-test-01 logo"
    left:
    - href: docs/index.qmd
      text: Overview
    # right:
    # - text: GitHub
    #   icon: github
    #   href: https://github.com/YOUR_ORG/YOUR_REPO


  sidebar:
    style: floating
    background: light
    contents:
    - docs/index.qmd
    - docs/guards/header.qmd
    - section: My Grafts
      contents:
      - _GRAFT_COLLAR: main
      - section: my-first-graft
        contents:
        - href: .grafts-cache/build/my-first-graft/docs/index.html
        - href: .grafts-cache/build/my-first-graft/docs/notebook.html
        - href: .grafts-cache/build/my-first-graft/docs/notebook copy.html
        - href: .grafts-cache/build/my-first-graft/docs/notebook copy 2.html
        - href: .grafts-cache/build/my-first-graft/docs/notebook copy 3.html
        - href: .grafts-cache/build/my-first-graft/docs/notebook copy 4.html
        - href: .grafts-cache/build/my-first-graft/docs/notebook copy 5.html
        - href: .grafts-cache/build/my-first-graft/docs/notebook copy 6.html
        - href: .grafts-cache/build/my-first-graft/docs/notebook copy 7.html
        _autogen_branch: graft/my-first-graft
    - section: Notes
      contents:
      - _GRAFT_COLLAR: notes
      - section: demo2
        contents:
        - .grafts-cache/build/demo2/docs/index.qmd
        - .grafts-cache/build/demo2/docs/app.qmd
        _autogen_branch: graft/demo2
    - section: Bugs
      contents:
      - _GRAFT_COLLAR: bugs
    - docs/guards/footer.qmd

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    grid:
      sidebar-width: 240px
      body-width: 1200px
      margin-width: 260px
    toc: true
    code-copy: true
    # code-overflow: wrap
    # code-tools: true
    code-fold: true
    code-summary: "Show the code"

    link-external-newwindow: true
    number-sections: false

highlight-style: a11y

execute:
  enabled: false

metadata:
  site_build: "pending"
