project:
  type: website
  output-dir: _site
  render:
    - "**/*.ipynb"
    - "**/*.md"
    - "**/*.qmd"

website:
  title: "my-first-graft"
  sidebar:
    style: floating
    contents:
      - href: docs/index.qmd
      - href: docs/notebook.ipynb
      - href: docs/notebook copy.ipynb
      - href: docs/notebook copy 2.ipynb
      - href: docs/notebook copy 3.ipynb
      - href: docs/notebook copy 4.ipynb
      - href: docs/notebook copy 5.ipynb
      - href: docs/notebook copy 6.ipynb
      - href: docs/notebook copy 7.ipynb

format:
  html:
    theme: cosmo
    toc: true

execute:
  enabled: false
