project:
  type: website
  output-dir: _site
  resources:
  - docs/favicon.svg
  - dist/my-first-graft/**/*.html
  - dist/second-graft/**/*.html
filters:
- docs/site-build.lua

website:
  title: "quarto-test-01"
  description: "Skeleton docs for branch-based Quarto builds."
  favicon: docs/favicon.svg
  # repo-url: https://github.com/YOUR_ORG/YOUR_REPO
  # repo-actions: [source, issue]
  page-footer:
    right: "Last build: {{< meta site_build >}}"

  navbar:
    title: "quarto-test-01"
    logo: docs/favicon.svg
    logo-alt: "quarto-test-01 logo"
    left:
    - href: docs/index.qmd
      text: Overview
    # right:
    # - text: GitHub
    #   icon: github
    #   href: https://github.com/YOUR_ORG/YOUR_REPO


  sidebar:
    style: floating
    background: light
    contents:
    - docs/index.qmd
    - docs/guards/header.qmd
    - section: My Grafts
      contents:
      - _GRAFT_COLLAR: main
      - section: my-first-graft
        contents:
        - href: dist/my-first-graft/docs/index.html
          text: Index
        - href: dist/my-first-graft/docs/notebook.html
          text: Notebook
        - href: dist/my-first-graft/docs/notebook copy.html
          text: Notebook Copy
        - href: dist/my-first-graft/docs/notebook copy 2.html
          text: Notebook Copy 2
        - href: dist/my-first-graft/docs/notebook copy 3.html
          text: Notebook Copy 3
        - href: dist/my-first-graft/docs/notebook copy 4.html
          text: Notebook Copy 4
        - href: dist/my-first-graft/docs/notebook copy 5.html
          text: Notebook Copy 5
        - href: dist/my-first-graft/docs/notebook copy 6.ipynb
        - href: dist/my-first-graft/docs/notebook copy 7.ipynb
        _autogen_branch: graft/my-first-graft
    - section: Notes
      contents:
      - _GRAFT_COLLAR: notes
    - section: Bugs
      contents:
      - _GRAFT_COLLAR: bugs
      - section: second-graft
        contents:
        - text: Index
          href: dist/second-graft/docs/index.html
        - text: App
          href: dist/second-graft/docs/app.html
        _autogen_branch: graft/second-graft
    - docs/guards/footer.qmd

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    grid:
      sidebar-width: 240px
      body-width: 1200px
      margin-width: 260px
    toc: true
    code-copy: true
    # code-overflow: wrap
    # code-tools: true
    code-fold: true
    code-summary: "Show the code"

    link-external-newwindow: true
    number-sections: false

highlight-style: a11y

execute:
  enabled: false

metadata:
  site_build: "pending"
